name: "Setup gradle"
description: "Setup gradle to run in a workflow - generally called from another composite action"

inputs:
  gradle-home-cache-cleanup:
    required: false
    default: "true"
    description: "Removing unused files from Gradle User Home before saving to cache"

runs:
  using: "composite"
  steps:
    - name: "Validate gradle wrapper"
      uses: gradle/actions/wrapper-validation@v4

    - name: "Setup Gradle build action"
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: current
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup }}