name: "Setup Gradle Signing Environment"
description: "Sets up gradle.properties and secret key ring for signing/publishing"
inputs:
  signing-key-id:
    required: true
  signing-password:
    required: true
  signing-key-base64:
    required: true
  maven-username:
    required: true
  maven-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: "Write gradle.properties"
      shell: bash
      run: |
        cat <<EOF >> gradle.properties
        signingInMemoryKeyId=${{ inputs.signing-key-id }}
        signingInMemoryKeyPassword=${{ inputs.signing-password }}
        signingInMemoryKey=${{ inputs.signing-key-base64 }}
        mavenCentralUsername=${{ inputs.maven-username }}
        mavenCentralPassword=${{ inputs.maven-password }}
        EOF
