name: "Setup Gradle Signing Environment"
description: "Sets up gradle.properties and secret key ring for signing/publishing"
inputs:
  gpg-key-b64:
    required: true
  signing-key-id:
    required: true
  signing-password:
    required: true
  maven-username:
    required: true
  maven-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: "Write gradle.properties"
      shell: bash
      run: |
        cat <<EOF >> gradle.properties
        signing.keyId=${{ inputs.signing-key-id }}
        signing.password=${{ inputs.signing-password }}
        signing.secretKeyRingFile=secring.gpg
        mavenCentralUsername=${{ inputs.maven-username }}
        mavenCentralPassword=${{ inputs.maven-password }}
        EOF

    - name: "Decode GPG key"
      shell: bash
      run: echo "${{ inputs.gpg-key-b64 }}" | base64 -d > secring.gpg