name: "Generate version information"
description: "Generate version information and expose using outputs"

inputs:
  release:
    description: "Set to true to generate release version information"
    required: false
    default: "false"

outputs:
  mobile-version-code:
    description: "Version code of application"
    value: ${{ steps.mobile_version_code.outputs.mobile_version_code }}

  mobile-version-name:
    description: "Version name of application"
    value: ${{ steps.mobile_version_name.outputs.mobile_version_name }}

runs:
  using: "composite"
  steps:
    - name: "Generate versions"
      id: version_code
      run: |
        if [ "${{ inputs.release }}" == "true" ]; then
          ./scripts/generate_versions.sh --release
        else
          ./scripts/generate_versions.sh
        fi
      shell: bash

    - name: "Get mobile version code"
      id: mobile_version_code
      run: echo "mobile_version_code=$(grep 'V_VERSION_CODE=' versions.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Get mobile version name"
      id: mobile_version_name
      run: echo "mobile_version_name=$(grep 'V_VERSION=' versions.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
      shell: bash
