name: Flow library release

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Checks
        run: ./gradlew :toggles-flow:check --exclude-task testReleaseUnitTest

      - name: Setup environment
        if: github.repository == 'erikeelde/toggles'
        run: |
          echo "signing.keyId=${{secrets.SIGNING_KEYID}}" >> gradle.properties
          echo "signing.password=${{secrets.SIGNING_PASSWORD}}" >> gradle.properties
          echo "signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
          echo "mavenCentralRepositoryUsername=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}" >> gradle.properties
          echo "mavenCentralRepositoryPassword=${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}" >> gradle.properties
          echo "${{secrets.SECRING_GPG_B64}}" > secring.gpg.b64
          base64 -d secring.gpg.b64 > secring.gpg

      - name: Publish flow library
        if: github.repository == 'erikeelde/toggles'
        run: ./gradlew :toggles-flow:publish --no-daemon --no-parallel
