name: Libraries snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: ./.github/actions/setup_android_and_java

      - name: "Calculate build number"
        id: version_information
        uses: ./.github/actions/version_information

      - name: Setup environment
        if: github.repository == 'erikeelde/toggles'
        run: |
          echo "signing.keyId=${{secrets.SIGNING_KEYID}}" >> gradle.properties
          echo "signing.password=${{secrets.SIGNING_PASSWORD}}" >> gradle.properties
          echo "signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
          echo "mavenCentralUsername=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}" >> gradle.properties
          echo "mavenCentralPassword=${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}" >> gradle.properties
          echo "${{secrets.SECRING_GPG_B64}}" > secring.gpg.b64
          base64 -d secring.gpg.b64 > secring.gpg

      - name: Publish snapshot libraries
        if: github.repository == 'erikeelde/toggles'
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache
