name: Manual release workflow

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name:
        run: |
          echo "${{secrets.SECRING_GPG_B64}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
          touch ~/.gradle/gradle.properties
          echo "signing.keyId=${{secrets.SIGNING_KEYID}}" >> ~/.gradle/gradle.properties
          echo "signing.password=${{secrets.SIGNING_PASSWORD}}" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=~/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
          echo "mavenCentralRepositoryUsername=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}" >> ~/.gradle/gradle.properties
          echo "mavenCentralRepositoryPassword=${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}" >> ~/.gradle/gradle.properties

      - name: Check out java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Detekt
        run: ./gradlew :toggles-prefs:detekt

      - name: Run Android Lint
        run: ./gradlew :toggles-prefs:lint

      - name: Run Android Unit test
        run: ./gradlew :toggles-prefs:testDebugUnitTest

      - name: Publish core library
        run: ./gradlew :toggles-prefs:publish --no-daemon --no-parallel
