name: Manual release workflow

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name:
        run: |
          echo "${{ secrets.KEYSTORE_PROPERTIES }} > keystore.properties.asc
          gpg -d --passphrase "${{ secrets.GPG_ENCRYPTION_KEY }}" --batch keystore.properties.asc > keystore.properties

          echo "${{ secrets.TOGGLES_KEYSTORE }} > toggles_keystore.jks.asc
          gpg -d --passphrase "${{ secrets.GPG_ENCRYPTION_KEY }}" --batch toggles_keystore.jks.asc > toggles_keystore.jks

          echo "${{ secrets.SERVICE_ACCOUNT }} > service_account.json.asc
          gpg -d --passphrase "${{ secrets.GPG_ENCRYPTION_KEY }}" --batch service_account.json.asc > service_account.json

      - name: Check out java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Android Checks
        run: ./gradlew check


      - name: Build apks
        run: ./gradlew :toggles-app:publish
