name: Prefs library release

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Check out java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Generate cache key
        run: ./scripts/checksum.sh ./ checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
            build-cache
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Run Checks
        run: ./gradlew :toggles-prefs:check --exclude-task testReleaseUnitTest

      - name: Setup environment
        if: github.repository == 'erikeelde/toggles'
        run: |
          echo "signing.keyId=${{secrets.SIGNING_KEYID}}" >> gradle.properties
          echo "signing.password=${{secrets.SIGNING_PASSWORD}}" >> gradle.properties
          echo "signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
          echo "mavenCentralRepositoryUsername=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}" >> gradle.properties
          echo "mavenCentralRepositoryPassword=${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}" >> gradle.properties
          echo "${{secrets.SECRING_GPG_B64}}" > secring.gpg.b64
          base64 -d secring.gpg.b64 > secring.gpg

      - name: Publish prefs library
        if: github.repository == 'erikeelde/toggles'
        run: ./gradlew :toggles-prefs:publish --no-daemon --no-parallel
