name: Pull request workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Android Linter
        run: ./gradlew lint

      - name: Upload lint reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Lint reports
          path: '**/build/reports/*'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload unit test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Unit test reports
          path: '**/build/reports/*'
