name: Pull request workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Check out java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run app Checks
        run: ./gradlew check

      - name: Run core Checks
        run: ./gradlew :toggles-core:check

      - name: Run flow Checks
        run: ./gradlew :toggles-flow:check --no-configuration-cache

      - name: Run flow noop Checks
        run: ./gradlew :toggles-flow-noop:check

      - name: Run prefs Checks
        run: ./gradlew :toggles-prefs:check --no-configuration-cache

      - name: Run prefs noop Checks
        run: ./gradlew :toggles-prefs-noop:check

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2
